name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    #- name: Set up Python
    #  uses: actions/setup-python@v5
    #  with:
    #    python-version: '3.12.x'

    #- name: Install Python dependencies
    #  run: |
    #    python -m pip install --upgrade pip
    #    pip install -r requirements.txt

    - name: Run Build
      run: ./build.sh

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit changes
      run: |
        rm -rf /tmp/docs-build
        mkdir -p /tmp/docs-build
        cp -r docs/* /tmp/docs-build/
        git checkout gh-pages || git checkout --orphan gh-pages
        rm -rf ./*
        cp -r /tmp/docs-build/* ./
        git add .
        if git diff --cached --quiet; then
          echo "No Changes To Commit ;-;"
        else
          git commit -m "Update Pages"
          git pull.rebase origin main
          git push origin gh-pages
        fi
        git status