name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    #- name: Set up Python
    #  uses: actions/setup-python@v5
    #  with:
    #    python-version: '3.12.x'

    #- name: Install Python dependencies
    #  run: |
    #    python -m pip install --upgrade pip
    #    pip install -r requirements.txt

    - name: Run Build
      run: ./build.sh

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit changes
      run: |
        git checkout gh-pages
        git add .
        git commit -m "Auto-commit: update from script" || echo "No changes to commit"
        git push